services:
  flask_app:

    # Build image dari Dockerfile
    build:
      context: ..    # Selalu arahkan ke root project, jika sudah di root cukup (.)
      dockerfile: container/Dockerfile.dev

    # Custom image name (ambil terlebih dahulu di docker hub, jika tidak ada maka lanjut ke proses build)
    image: flask_dev:v1
    pull_policy: never   # Supaya tidak mencoba pull ke Docker Hub (jika memang ada bisa hapus baris ini)

    # Custom container name
    container_name: sample_vps_flask_dev

    # Expose internal port antar container (biasa digunakan untuk reverse & forward proxy)
    expose:
      - "5000"

    # # Untuk testing di browser (tidak menggunakan reverse & forward proxy)
    # ports:
    #   - "5000:5000"

    volumes:
      # Bind Mount (selalu arahkan ke root project, jika sudah di root cukup (.))
      - ..:/app

    restart: unless-stopped


  caddy:

    # Pull dari official image
    image: caddy:2
    
    # Custom container name
    container_name: sample_vps_caddy_dev

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - flask_app

    volumes:
      # Bind Mount
      - ../images/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - ../logs:/var/log/caddy

      # Named Volume
      - caddy_data:/data
      - caddy_config:/config

    restart: unless-stopped


volumes:
  caddy_data:
  caddy_config: