FROM python:3.12-slim-bookworm

# Prevent python from writing pyc files & buffering stdout
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=development

# mengarah ke directory di dalam container
WORKDIR /app

# Install python dependencies
COPY requirements.txt .

# Running dependency
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy project (di dev biasanya akan dioverride volume)
COPY . .

# Expose port dev
EXPOSE 5000

# Dev server (auto reload)
CMD ["python", "run.py"]
